name: FreeForYoung SG Ultra V2

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

concurrency:
  group: freeforyoung-sg-ultra-v2
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Xray
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip curl

          curl -L \
          https://github.com/XTLS/Xray-core/releases/download/v1.8.24/Xray-linux-64.zip \
          -o /tmp/xray.zip

          mkdir -p /tmp/xray
          unzip -o /tmp/xray.zip -d /tmp/xray

          chmod +x /tmp/xray/xray

          echo "XRAY_PATH=/tmp/xray/xray" >> $GITHUB_ENV

      - name: Build Singapore VPN
        run: |
          python scripts/build_v2.py

      - name: Save result
        run: |
          git config user.name "FreeForYoung Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add output/

          git commit -m "Update Singapore servers" || exit 0

          git push
